version: '3.9'

services:
  # Node api service
  gpt-service:
    build: .
    ports:
      - "3008:3008"
    env_file:
      - .env
    networks:
      - my-net

networks:
  my-net:
    driver: bridge
