version: "3.9"

services:
  frontend:
    build: ./Frontend
    ports:
      - 3001:3001
    volumes:
      - ./Frontend:/app
    env_file:
      - ./Frontend/.env
    networks:
      - peer-prep-network

  user-service:
    build: ./UserService
    ports:
      - 3002:3002
    volumes:
      - ./UserService:/app
    networks:
      - peer-prep-network
  
  user-service-database:
    image: mongo:latest
    ports:
      - 27018:27017
    volumes:
      - ./UserServiceDatabase:/data/db
    networks:
      - peer-prep-network

  question-service:
    build: ./QuestionService
    ports:
      - "3003:3003"
    depends_on:
      - question-service-database
    networks:
      - peer-prep-network

  question-service-database:
    image: mongo:latest
    ports:
      - "27019:27017"
    networks:
      - peer-prep-network

  matching-service:
    build: ./MatchingService
    ports:
      - "3004:3004"
    depends_on: 
      - matching-service-database
      - rabbitmq
    networks:
      - peer-prep-network

  matching-service-database:
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - peer-prep-network

  # Rabbitmq service
  rabbitmq:
    image: rabbitmq:latest
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    networks:
      - peer-prep-network

  collaboration-service:
    build: ./CollaborationService
    ports:
      - "3005:3005"
    depends_on: 
      - collaboration-service-database
    networks:
      - peer-prep-network

  collaboration-service-database:
    image: mongo:latest
    ports:
      - "27021:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - peer-prep-network

  communication-service:
    build: ./CommunicationService
    ports:
      - "3007:3007"
    networks:
      - peer-prep-network

  gpt-service:
    build: ./GptService
    ports:
      - "3008:3008"
    env_file:
      - ./gpt-service/.env
    networks:
      - peer-prep-network

networks:
  peer-prep-network:
    driver: bridge
