version: '3.9'

app-service:
  env_file:
    - .env
    
services:
  # Node api service
  api:
    build: .
    ports:
      - "3004:3004"
    environment:
      PORT: 3004
    networks:
      - my-net

networks:
  my-net: