version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-net

  # Node api service
  api:
    build: .
    ports:
      - "3002:3002"
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: peer-prep
    depends_on: 
      - mongo_db
    networks:
      - my-net

volumes:
  mongo_data: 
    driver: local

networks:
  my-net: