version: '3.9'

services:
  # Mongodb service
  matching-service-database:
    container_name: db_container
    image: mongo:latest
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - my-net

  # Rabbitmq service
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:latest
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    networks:
      - my-net

  # Node api service
  matching-service:
    build: .
    ports:
      - "3004:3004"
    depends_on: 
      - matching-service-database
      - rabbitmq
    networks:
      - my-net

volumes:
  mongo_data: 
    driver: local

networks:
  my-net:
    driver: bridge