version: '3'
services:
  question-service-database:
    image: mongo:latest
    ports:
      - "27019:27017"

  question-service:
    build: .
    ports:
      - "3003:3003"
    depends_on:
      - question-service-database
