name: Build And Test Communication Service

on:
  push:
    paths:
      - "CommunicationService/**"
      - ".github/workflows/build_and_test_master_communication_service.yaml"

  pull_request:
    paths:
      - "CommunicationService/**"
      - ".github/workflows/build_and_test_master_communication_service.yaml"

jobs:
  build-and-test-communication-service:
    runs-on: ubuntu-latest

    env:
      CONTAINER_NAME: "ay2324s1-course-assessment-g16_communication-service_1" # Here _ is being used after file directory and service name vs -

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v3

      - name: Build Communication Service with Docker Compose
        run: docker-compose build --no-cache communication-service

      - name: Run Communication Service with Docker Compose
        run: docker-compose up -d communication-service

      # - name: Wait For Startup
      #   run: sleep 30

      - name: List Docker Containers
        run: docker ps

      - name: Logs [For Checking Status Only]
        run: docker-compose logs

      - name: Run Test Cases in Communication Service
        run: docker exec $CONTAINER_NAME npm test

      - name: Retrieve Artifacts [JEST Test Reports]
        run: docker cp $CONTAINER_NAME:/usr/src/app/coverage ./communication-service-test-jest-reports

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: communication-service-test-jest-report-artifacts
          path: ./communication-service-test-jest-reports/*

      - name: Shut Down Containers
        run: docker-compose down
