name: Build And Test Frontend Client

on:
  push:
    paths:
      - "Frontend/**"
      - ".github/workflows/build_and_test_master_frontend_client.yaml"

  pull_request:
    paths:
      - "Frontend/**"
      - ".github/workflows/build_and_test_master_frontend_client.yaml"

jobs:
  build-and-test-frontend-service:
    runs-on: ubuntu-latest

    env:
      CONTAINER_NAME: "ay2324s1-course-assessment-g16_frontend_1" # Here _ is being used after file directory and service name vs -

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Client with Docker Compose
        run: docker-compose build --no-cache frontend

      - name: Run Frontend Client with Docker Compose
        run: docker-compose up -d frontend

      # - name: Wait For Startup
      #   run: sleep 30

      - name: List Docker Containers
        run: docker ps

      - name: Logs [For Checking Status Only]
        run: docker-compose logs

      # - name: Run Test Cases in Frontend Client
      #   run: docker exec $CONTAINER_NAME npm test

      # - name: Retrieve Artifacts [JEST Test Reports]
      #   run: docker cp $CONTAINER_NAME:/app/coverage ./frontend-client-test-jest-reports

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: frontend-client-test-jest-report-artifacts
      #     path: ./frontend-client-test-jest-reports/*

      - name: Shut Down Containers
        run: docker-compose down
