name: Build And Test User Service

on:
  push:
    paths:
      - "UserService/**"

  pull_request:
    paths:
      - "UserService/**"

jobs:
  build-and-test-user-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v3

      - name: Build User Service and User Service Dtaabase with Docker Compose
        run: docker-compose build --no-cache user-service user-service-database

      - name: Run User Service and User Service Database with Docker Compose
        run: docker-compose up user-service user-service-database -d

      - name: Run Test Cases in User Service
        run: docker exec ay2324s1-course-assessment-g16-user-service-1 npm test

      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: user-service-test-artifacts
      #     path: path/to/artifacts

      - name: Shut Down Containers
        run: docker-compose down
