name: Build And Test GPT Service

on:
  push:
    paths:
      - "GptService/**"
      - ".github/workflows/build_and_test_master_gpt_service.yaml"

  pull_request:
    paths:
      - "GptService/**"
      - ".github/workflows/build_and_test_master_gpt_service.yaml"

jobs:
  build-and-test-gpt-service:
    runs-on: ubuntu-latest

    env:
      CONTAINER_NAME: "ay2324s1-course-assessment-g16_gpt-service_1" # Here _ is being used after file directory and service name vs -

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v3

      - name: Build GPT Service with Docker Compose
        run: docker-compose build --no-cache gpt-service

      - name: Run GPT Service with Docker Compose
        run: docker-compose up -d gpt-service

      # - name: Wait For Startup
      #   run: sleep 30

      - name: List Docker Containers
        run: docker ps

      - name: Logs [For Checking Status Only]
        run: docker-compose logs

      - name: Create New Environment File With GPT API Key
        run: docker exec $CONTAINER_NAME echo GPT_API_KEY=${{ secrets.GPT_API_KEY }} > ./usr/src/app/.env

      - name: Run Test Cases in GPT Service
        run: docker exec $CONTAINER_NAME npm test

      - name: Retrieve Artifacts [JEST Test Reports]
        run: docker cp $CONTAINER_NAME:/usr/src/app/coverage ./gpt-service-test-jest-reports

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: gpt-service-test-jest-report-artifacts
          path: ./gpt-service-test-jest-reports/*

      - name: Shut Down Containers
        run: docker-compose down
