name: Build And Test History Service

on:
  push:
    paths:
      - "HistoryService/**"
      - ".github/workflows/build_and_test_master_history_service.yaml"

  pull_request:
    paths:
      - "HistoryService/**"
      - ".github/workflows/build_and_test_master_history_service.yaml"

jobs:
  build-and-test-history-service:
    runs-on: ubuntu-latest

    env:
      CONTAINER_NAME: "ay2324s1-course-assessment-g16_history-service_1" # Here _ is being used after file directory and service name vs -

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Environment
        uses: docker/setup-buildx-action@v3

      - name: Build History Service and History Service Database with Docker Compose
        run: docker-compose build --no-cache history-service history-service-database

      - name: Run History Service and History Service Database with Docker Compose
        run: docker-compose up -d history-service history-service-database

      - name: Wait For Startup of MySQL Container
        run: sleep 15

      - name: List Docker Containers
        run: docker ps

      - name: Logs [For Checking Status Only]
        run: docker-compose logs

      - name: Run Test Cases in History Service
        run: docker exec $CONTAINER_NAME npm test

      - name: Retrieve Artifacts [JEST Test Reports]
        run: docker cp $CONTAINER_NAME:/app/coverage ./history-service-test-jest-reports

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: history-service-test-jest-report-artifacts
          path: ./history-service-test-jest-reports/*

      - name: Shut Down Containers
        run: docker-compose down
